repos:
    # Black - Python code formatter
    - repo: https://github.com/psf/black
      rev: 24.10.0
      hooks:
          - id: black
            language_version: python3
            args: [--config=pyproject.toml]

    # isort - Python import organizer (compatible with Black)
    - repo: https://github.com/pycqa/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: [--settings-path=pyproject.toml]

    # Ruff - Fast Python linter (no auto-fix, just report)
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.8.4
      hooks:
          - id: ruff
            args: [--config=pyproject.toml]

    # General hooks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-toml
